### PR TITLE
Added a note for the current functionality to 'readme.md'.

### PR DESCRIPTION
**Pull request by evandrocoan**

### CODE REVIEW

**Comment by facelessuser** [comment]
I have to be honest, I don't think this is necessary.

1. If ApplySyntax didn't force the setting of the syntax, what would be the point?

2.  I cover what the `extension` parameter does here noting that it adds the extension to the language setting file: http://facelessuser.github.io/ApplySyntax/usage/#extensions.

3. ApplySyntax doesn't have to add the extensions to your settings file.  There is actually a setting to turn this off in the settings file, and it is documented: http://facelessuser.github.io/ApplySyntax/usage/#extensions.

**Comment by evandrocoan** [comment]
> If ApplySyntax didn't force the setting of the syntax, what would be the point?

I agree with it. This package would be unnecessary.

This pull request would be just a message to clarify to the unaware user like me, to exactly what is this package going to do, and to take care while reading the configuration file.

> ApplySyntax doesn't have to add the extensions to your settings file. There is actually a setting to turn this off.

Adding this note to the first read-me page would be as good as set this setting as disabled by default. So, either this or that. Because how would I guess this package is going to override my personal settings files, which I personally wrote by hand. I was expecting it to change the default package settings syntax definitions, not mime syntax definitions.

Also, I changed the file `ApplySyntax.ext-list` removing the '.inc' from PHP and adding it to Pawn. Why the was overridden?
```
    // Auto add extensions to language settings file in User folder.
    // Do not manually remove "ApplySyntax.ext-list" from the User folder
    // as it is used to track which extensions ApplySyntax added so
    // they can be removed later if needed.
    // "extenstions" are ignored by "match": "all" setting.
    "add_exts_to_lang_settings": true,
```

So, setting it to false would not override my settings on the user folder, only the default package's settings. Then setting by default `add_exts_to_lang_settings` as false is not a good option thought because it would looks like the plugin is not working on case the user some time set some file extension. Anyways, if you want to you can merge this, if not just close this pull request, later anyone else which troubles as I, will may find this googling it, and get to know what to do.

**Comment by facelessuser** [comment]
>  Because how would I guess this package is going to override my personal settings files, which I personally wrote by hand.

By reading the documentation.  If you turn off the setting, ApplySyntax will remove any it added.

> I was expecting it to change the default package settings syntax definitions, not mime syntax definitions.

No, I would never modify the syntax definitions.  I'm not sure what you are referring to here.  The only thing ApplySyntax changes is the syntax language setting.  It doesn't modify mime settings.  It doesn't modify your syntax definitions either.  The only reason it adds to the language settings file is to ensure you get proper file icons in Sublime as that is the only way to ensure proper icons get used. Rules that cannot be defined by the `extensions` param (or simply aren't defined there) don't get the proper icons.  If this isn't a problem, they can be turned off.

> Then setting by default add_exts_to_lang_settings as false is not a good option thought because it would looks like the plugin is not working on case the user some time set some file extension

ApplySyntax will always ensure it sets the syntax regardless of what extensions a user adds to their language settings.  The idea is that a user would keep all their rules defined in ApplySyntax.  Again, if you don't want ApplySyntax managing that, turn it off.  But ApplySyntax will always load the defined syntax that is defined in its rules regardless of what `add_exts_to_lang_settings` is set to or what you set in your in your language settings.

**Comment by facelessuser** [comment]
I just don't see why I need this note when the entire Usage guide is about configuring your rules to **force** your syntax.

**Pull request closed without merging**
