### PR TITLE
Add syntax rule for Matlab files

### PR DESCRIPTION
**Pull request by xhacker**

### CODE REVIEW

**Comment by facelessuser** [comment]
I have a concern that your `contains` rule is not sufficient.

- What if there are no comments in your particular Matlab file?
- What if for some reason a line continuation is  used in Objective-C such that a modulo operator starts the next line.

I am always hesitant to include `contains` rules by default because, by their nature, performance can be poor on large files as it could potentially scan the entire file before stopping.  As this `contains` rule looks like it can easily be broken, I am not sure how I feel about making it a default rule.

**Comment by facelessuser** [comment]
You can ignore the Travis failures.  Apparently some changes were made to the PEP257 linting modules that now forbid new lines before class docstrings.  I will have to fix those separately.

**Comment by xhacker** [comment]
@facelessuser: Your concern is fair. For the false positive, I could use a regex for Objective-C like [this](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb#L69) first. For the performance concern, do you have any suggestions?

**Comment by facelessuser** [comment]
> For the false positive, I could use a regex for Objective-C like this first.

Try it out and see how reliable it is.  I don't use Objective-C, so I am obviously not an expert, but based on what I *do* know, `%` would be extremely unreliable.

> For the performance concern, do you have any suggestions?

You've already limited the check to require the file to be a `.m` file first, so that will keep it from running on other file types; that is good.  My point is, if we are going to subject all `.m` files to a `contains` rule, which may end up scanning the whole file, you need to make the scan count; make it as reliable as possible.  I don't want a contains rule that has bad performance **and** bad heuristics if it is going to enabled on **everyone**'s `.m` files by default; it's not worth it.  So experiment with other regex because I don't have any confidence in the current `%` search.

**Comment by facelessuser** [comment]
Should I leave this open?  I am in no rush, but I am interested in whether you have plans to continue moving forward.  Thanks.

**Comment by xhacker** [comment]
Hi please leave this open, I still want to implement it. Just a little busy these days. :)

**Comment by facelessuser** [comment]
No worries, I just wanted to make sure I didn't scare you off :smile:.

**Comment by xhacker** [comment]
I just added some more advanced regex. I’ve tested a bunch of Objective-C and Matlab files, it mostly worked fine. The only case is that it can’t detect Matlab files with no comments in it.

**Comment by facelessuser** [comment]
So if the objective C check is really good, do you need a matlab `contains` check?  Can the `filepath` check be sufficient in this case?

Apply syntax will evaluate objective C first, and if that matches, it will never make it to matlab, and if it doesn't match objective C, we assume matlab.

**Comment by xhacker** [comment]
I can’t say the Objective-C regex could detect 100% of the objc files, so I think the Matlab check is still necessary.

**Comment by facelessuser** [comment]
I guess that is fair to have it not trigger if it isn't sure.  It is better to have it not recognize than to recognize incorrectly.  I will probably accept this.  Thanks for all your work hunting down the best way.  I imagine this isn't the only project that struggles with matlab vs objective-c.

**Comment by xhacker** [comment]
Totally agree, it would be better to mark Matlab files at Matlab. But if unsure, I’d rather keep it as objc.

Thanks for your plugin anyway :)

**Pull request merged**
