### PR TITLE
Fix for #93, project specific syntaxes setting not working bug

### PR DESCRIPTION
**Pull request by jahan01**

### CODE REVIEW

**Comment by facelessuser** [comment]
Thanks so much for taking the time to do this.  I actually have a fix locally that I am to merge soon.   Just been busy.  Instead of looking for a setting that is namespaced with "project" prefixed to it, I am taking the approach of simply calling a method "get_project_setting".  There is one place it needs to be called, so that should be sufficient.  I will try and get it in soon.

Thanks!

**Comment by jahan01** [comment]
I see, this was my first time ever working with a sublime text plugin's so I may be missing the "correct/perfect" way of doing things. Currently for any changes in global user specific settings to take effect, I have to restart sublime text every single time. That is the reason I read project specific settings for every file load event, not just at the plugin_loaded() phase.

**Comment by facelessuser** [comment]
> Currently for any changes in global user specific settings to take effect, I have to restart sublime text every single time. That is the reason I read project specific settings for every file load event, not just at the plugin_loaded() phase.

This is not the case.  Global settings are reloaded when they are changed, but if ApplySyntax has already touched a view, it will not alter the syntax even if you changed the settings.  This is because you might purposely change the syntax for a specific reason, and it would be annoying to have ApplySyntax to presume that you don't know what you are doing and override what you did.  Now if you change the file name, then ApplySyntax should kick in.  If you close the file and reopen it, ApplySyntax will kick it as well.

I am glad you brought this point up though, as my fix actually is loading it every time as yours does, but it shouldn't.  Once ApplySyntax touches a file on load or new etc., it should not modify the setting unless the file is reopened or renamed.

What actually should happen is project settings should be written to the active view on load and accessed there.

**Comment by facelessuser** [comment]
Never mind this isn't true either.  On save **should** reload the syntax, it won't change the syntax just because you update your settings file for the reason I listed above.  You will have to save the file or manually set your syntax for the change to take place.  This is reasonable.

**Comment by facelessuser** [comment]
Anyways global settings file work fine, if you are having global settings issues please describe your issue as I don't understand what you are referring to.

**Comment by jahan01** [comment]
I just tested it out. On saving the 'touched' file the syntax is not reloaded. I have to restart sublime text to make ApplySyntax to apply updated settings.

**Comment by facelessuser** [comment]
Give me a step by step I can reproduce as my testing shows otherwise.

**Comment by jahan01** [comment]
Below are the steps to reproduce:
I use sublime text 3 Build no: 3083

1. Open a file first without any change to ApplySyntax user settings.
2. Change the user settings in ApplySyntax to change syntax for the file opened in step 1.
3. Switch to the opened file. No syntax change should have been applied.
4. Save the file. No syntax change this time also.
5. Close the file and reopen. No syntax change yet.
6. Close the file and restart the sublime text.
7. Now open the same file. Syntax change is applied this time.

I am not really sure if this is designed to work as above.

**Comment by facelessuser** [comment]
This is not what I see.  I have a custom rule in my global settings:

```js
        {
            "syntax": "AAALanguages/Better JSON/JSON",
            "extensions": [
                "json", "tweak-settings", "jarvis-conf",
                "jarvis-lang", "sublime-settings",
                ".jscsrc", ".jshintrc", ".csslintrc",
                ".bowerrc", ".eslintrc", "sublime-theme"
            ]
        },
```

1. I open a sublime-settings file and Apply Syntax applies my custom JSON syntax above.
2. I edit the rule to something absurd like `Makefile/Makefile` and save the settings file.
3. I then switch to the previously opened sublime-settings file and save.  Syntax changes to `Makefile/Makefile`.

This is what I see.

**Comment by jahan01** [comment]
That sounds weird.

I have something like this. Anyfile inside folder __ansible__ will have Ansible syntax applied.

    "syntaxes": [
            {
                "syntax": "Ansible/Ansible",
                "rules": [
                    {"file_path": ".*\\\\ansible(\\\\..*)?$"},
                    {"file_path": ".*/ansible(/..*)?$"},
                ]
            },
        ],

1. I open a _yml_ file inside __ansible__ folder. I get ansible syntax.
2. I change the rule to something like `Ruby/Ruby` and save setting file
3. I switch to the previously opened yml file and save. Syntax doesn't change, it remains still as Ansible
4. I close the _yml_ file and restart sublime text. 
5. Open the _yml_ file. Now syntax is changed to `Ruby/Ruby`

Config:
Sublime Text v3
Build: 3083
OS: Win 7

I am attaching screen cast for what I did earlier.

[Screen Record.zip](https://github.com/facelessuser/ApplySyntax/files/111732/Screen.Record.zip)

**Comment by facelessuser** [comment]
I'll give your example a try tomorrow when I have some more time and let you know what I find.

**Pull request closed without merging**
