### PR TITLE
Let ST handle Git files naturally

### LINKED ISSUE #116: Remove Git files from the INI/INI `default_syntaxes` preset
With the new release of ST3.1, there are built-in syntax files for "Git Formats." ApplySyntax doesn't need to map them to the INI package anymore.

If you want to, you can also make a special rule for `.git/config` like this one from my `ApplySyntax.sublime-settings` user file:

```js
        {
            "syntax": "Git Formats/Git Config",
            "rules": [
                {"file_path": ".*(\\\\|/)\\.git(\\\\|/)config(~\\w*)?"},
                {"file_path": ".*(\\\\|/)git_config(~\\w*)?$"},
            ],
        }
```

If you want, I can submit this directly as a PR when I get a chance.

### PR DESCRIPTION
**Pull request by michaelblyons**
Fixes #116

### CODE REVIEW

**Comment by facelessuser** [comment]
Test failures can be ignored as they are unrelated; I have to update the document handling portion as things have changed.

I don't initially see any issues, but I'll take a closer look tomorrow.  Thanks for the pull!

**Comment by facelessuser** [comment]
Isn't it `\\.git` already? It an I missing something?

**Comment by michaelblyons** [comment]
Both the removed and added lines look kind of like this:

```json
    {"file_path": ".*/git/config$"},
    {"file_path": ".*\\\\git\\\\config$"}
```
which will match `**/git/config`. But I think they should be 

```json
    {"file_path": ".*/\\.git/config$"},
    {"file_path": ".*\\\\\\.git\\\\config$"}
```
to match `**/.git/config`. Note the dot that is present here, but missing in the first set.

I have an additional rule in my local settings that is masking the problem for me, so I didn't notice the lack of the dot.

**Comment by facelessuser** [comment]
Huh, yup, we are missing the dot.

**Pull request merged**
